- name: 3.1 Enable security auditing
  tags: level_1
  command: launchctl load -w /System/Library/LaunchDaemons/com.apple.auditd.plist

# 3.2 Configure Security Auditing Flags per local organizational requirements is a Level 2 Remediation

- name: 3.3 Retain install.log for 365 or more days with no maximum size 
  tags: level_1
  command: |
    installRetention="$(grep -i ttl /etc/asl/com.apple.install | awk -F'ttl=' '{print $2}')"
	  if [[ "$installRetention" = "" ]]; then
		  mv /etc/asl/com.apple.install /etc/asl/com.apple.install.old
		  sed '$s/$/ ttl=365/' /etc/asl/com.apple.install.old > /etc/asl/com.apple.install
    elif [[ "$installRetention" -lt "365" ]]; then
		  mv /etc/asl/com.apple.install /etc/asl/com.apple.install.old
		  sed "s/"ttl=$installRetention"/"ttl=365"/g" /etc/asl/com.apple.install.old > /etc/asl/com.apple.install
    fi

- name: 3.4 Ensure security auditing retention 
  tags: level_1
  ansible.builtin.lineinfile:
    path: /etc/security/audit_control 
    regexp: 'expire-after:'
    line: expire-after:60d 

- name: 3.5 Control access to audit records
  tags: level_1
  command: |
    chown -R root:wheel /etc/security/audit_control
    chmod -R -o-rw /etc/security/audit_control
    chown -R root:wheel /var/audit/
    chmod -R -o-rw /var/audit/

- name: 3.6 Ensure Firewall is configured to log 
  tags: level_1
  command: /usr/libexec/ApplicationFirewall/socketfilterfw --setloggingmode on

# 3.7 Software Inventory Considerations is a level 2 remediation 
