- name: Install Retention 
  shell: grep -i ttl /etc/asl/com.apple.install | awk -F'ttl=' '{print $2}'
  register: install_retention

- name: 3.1 Enable security auditing
  tags: level_1
  command: launchctl load -w /System/Library/LaunchDaemons/com.apple.auditd.plist

- name: 3.3 Retain install.log for 365 or more days with no maximum size (1)
  tags: level_1
  ansible.builtin.lineinfile:
    path: /etc/asl/com.apple.install
    regexp: ttl=
    line: ttl=365
  when: install_retention.stdout == ""
  register: install_retention_done

- name: 3.3 Retain install.log for 365 or more days with no maximum size (2)
  tags: level_1
  ansible.builtin.lineinfile:
    path: /etc/asl/com.apple.install
    regexp: ttl=\d+
    line: ttl=365
  when: install_retention.stdout|int < 365

- name: 3.3 Retain install.log for 365 or more days with no maximum size (3)
  tags: level_1
  ansible.builtin.lineinfile:
    path: /etc/asl/com.apple.install
    regexp: all_max=
    state: absent

- name: 3.4 Ensure security auditing retention 
  tags: level_1
  ansible.builtin.lineinfile:
    path: /etc/security/audit_control 
    regexp: 'expire-after:'
    line: expire-after:60d 

- name: 3.5 Control access to audit records (1)
  tags: level_1
  ansible.builtin.file:
    path: /etc/security/audit_control
    owner: root
    group: wheel
    mode: -o-rw

- name: 3.5 Control access to audit records (2)
  tags: level_1
  ansible.builtin.file:
    path: /var/audit/
    owner: root
    group: wheel
    mode: -o-rw
    state: directory
    recurse: yes
    
- name: 3.6 Ensure Firewall is configured to log 
  tags: level_1
  command: /usr/libexec/ApplicationFirewall/socketfilterfw --setloggingmode on
