- name: 3.1 Enable security auditing
  tags: level_1
  command: launchctl load -w /System/Library/LaunchDaemons/com.apple.auditd.plist

# 3.2 Configure Security Auditing Flags per local organizational requirements is a Level 2 Remediation

- name: 3.3 Retain install.log for 365 or more days with no maximum size 
  tags: level_1
  command: |
    installRetention="$(grep -i ttl /etc/asl/com.apple.install | awk -F'ttl=' '{print $2}')"
	  if [[ "$installRetention" = "" ]]; then
		  mv /etc/asl/com.apple.install /etc/asl/com.apple.install.old
		  sed '$s/$/ ttl=365/' /etc/asl/com.apple.install.old > /etc/asl/com.apple.install
    elif [[ "$installRetention" -lt "365" ]]; then
		  mv /etc/asl/com.apple.install /etc/asl/com.apple.install.old
		  sed "s/"ttl=$installRetention"/"ttl=365"/g" /etc/asl/com.apple.install.old > /etc/asl/com.apple.install
    fi

- name: 3.4 Ensure security auditing retention 
  tags: level_1
  ansible.builtin.lineinfile:
    path: /etc/security/audit_control 
    regexp: 'expire-after:'
    line: expire-after:60d 

- name: 3.5 Control access to audit records (1)
  tags: level_1
  ansible.builtin.file:
    path: /etc/security/audit_control
    owner: root
    group: wheel
    mode: -o-rw

- name: 3.5 Control access to audit records (2)
  tags: level_1
  ansible.builtin.file:
    path: /var/audit/
    owner: root
    group: wheel
    mode: -o-rw
    state: directory
    recurse: yes
    
- name: 3.6 Ensure Firewall is configured to log 
  tags: level_1
  command: /usr/libexec/ApplicationFirewall/socketfilterfw --setloggingmode on

# 3.7 Software Inventory Considerations is a level 2 remediation 
