- name: 4.1 Disable Bonjour advertising service 
  tags: level_2
  shell: defaults write /Library/Preferences/com.apple.mDNSResponder.plist NoMulticastAdvertisements -bool true

- name: 4.1 Disable Bonjour advertising service
  tags: level_2
  osx_defaults:
    domain: /Library/Preferences/com.apple.mDNSResponder.plist
    key: NoMulticastAdvertisements
    type: int 
    value: '1'
  become: yes 

- name: 4.2 Enable "Show Wi-Fi status in menu bar"
  tags: level_1
  shell: | 
    su "{{ item }}"
    defaults -currentHost write com.apple.controlcenter.plist WiFi -int 18 
  with_items: "{{ users }}"

- name: 4.4 Ensure http server is not running 
  tags: level_1
  command: launchctl disable system/org.apache.httpd

- name: 4.5 Ensure nfs server is not running. 
  tags: level_1 
  command: |
    launchctl disable system/com.apple.nfsd 
    rm /etc/exports
