- name: Bluetooth Power state
  osx_defaults:
    domain: com.apple.Bluetooth
    key: ControllerPowerState
  shell: defaults read /Library/Preferences/com.apple.Bluetooth ControllerPowerState
  register: bt_power

- name: Bluetooth Paired Devices
  shell: "system_profiler SPBluetoothDataType 2>/dev/null | grep -m1 Paired: Yes"
  register: bt_datatype
  ignore_errors: yes

- name: FileVault Status
  shell: fdesetup status
  register: filevault_status

- name: Top Left Corner Value
  shell: defaults read com.apple.dock wvous-tl-corner
  ignore_errors: yes
  register: cornerone

- name: Bottom Left Corner Value
  shell: defaults read com.apple.dock wvous-bl-corner
  ignore_errors: yes
  register: cornertwo

- name: Top Right Corner Value
  shell: defaults read com.apple.dock wvous-tr-corner
  ignore_errors: yes
  register: cornerthree

- name: Bottom Right Corner Value
  shell: defaults read com.apple.dock wvous-br-corner
  ignore_errors: yes
  register: cornerfour

- name: Fix Top Left Corner
  osx_defaults: 
    domain: com.apple.dock
    key: wvous-tl-corner
    type: int
    value: '0' 
  register: corneronefix

- name: Fix Bottom Left Corner 
  osx_defaults: 
    domain: com.apple.dock
    key: wvous-bl-corner
    type: int
    value: '0'
  register: cornertwofix 

- name: Fix Top Right Corner
  osx_defaults:
    domain: com.apple.dock
    key: wvous-tr-corner
    type: int
    value: '0' 
  register: cornerthreefix

- name: Fix Bottom Right Corner 
  osx_defaults: 
    domain: com.apple.dock
    key: wvous-br-corner
    type: int
    value: '10'
  register: cornerfourfix

- name: 2.1.1 Turn off Bluetooth, if no paired devices exist (1)
  tags: level_1
  osx_defaults:
    domain: /Library/Preferences/com.apple.Bluetooth
    key: ControllerPowerstate
    type: int
    value: '0'
  when: bt_power.stdout|int == 1 and bt_datatype.stdout == ""

- name: 2.1.1 Turn off Bluetooth, if no paired devices exist (2)
  tags: level_1
  shell: killall -HUP blued
  when: bt_power.stdout|int == 1 and bt_datatype.stdout == ""
  register: kill_bt
  failed_when: kill_bt.rc > 1

- name: 2.1.2 Show Bluetooth status in menu bar 
  tags: level_1
  osx_defaults:
    domain: com.apple.controlcenter.plist
    key: Bluetooth
    type: int
    value: '18'
  become_user: target_user
  become: true

- name: "2.2.1 Enable Set time and date automatically"
  tags: level_1
  command: "{{ item }}"
  with_items:
    - systemsetup -setnetworktimeserver time.apple.com
    - systemsetup -setusingnetworktime on

- name: "2.2.2 Ensure time set is within appropriate limits"
  tags: level_1
  command: systemsetup -getnetworktimeserver

- name: "2.3.1 Set an inactivity interval of 20 minutes or less for the screen saver"
  tags: level_1
  osx_defaults: 
    domain: com.apple.screensaver
    key: idleTime
    type: int
    value: '1200'
  become_user: target_user
  become: true

- name: 2.3.2 Secure screen saver corners (Top Left) 
  tags: level_2
  command: | 
    su "{{ target_user }}" 
    corneronefix
  when: cornerone|int == 6 or cornerone.rc == 1

- name: 2.3.2 Secure screen saver corners (Bottom Left)
  tags: level_2
  command: |
    su "{{ target_user }}"
    cornertwofix
  when: cornertwo|int == 6 or cornertwo.rc == 1

- name: 2.3.2 Secure screen saver corners (Top Right)
  tags: level_2
  command: |
    su "{{ target_user }}"
    cornerthreefix
  when: cornerthree|int == 6 or cornerthree.rc == 1

- name: 2.3.2 Secure screen saver corners (Bottom Right)
  tags: level_2
  command: |
    su "{{ target_user }}"
    cornerfourfix
  when: cornerfour|int == 6 or cornerfour.rc == 1

- name: "2.4.1 Disable Remote Apple Events"
  tags: level_1
  command: systemsetup -setremoteappleevents off
  when: full_disk_access == "true"

- name: 2.4.2 Disable Internet Sharing
  tags: level_1
  osx_defaults: 
    domain: /Library/Preferences/SystemConfiguration/com.apple.nat
    key:  NAT -dict Enabled
    type: int
    value: '0'

- name: "2.4.3 Disable Screen Sharing"
  tags: level_1
  command: launchctl disable system/com.apple.screensharing

- name: "2.4.4 Disable printer Sharing"
  tags: level_1
  command: cupsctl --no-share-printers

- name: "2.4.5 Disable Remote Login"
  tags: level_1
  shell: yes yes | systemsetup -setremotelogin off

- name: "2.4.6 Disable DVD or CD Sharing"
  tags: level_1
  command: launchctl disable system/com.apple.ODSAgent

- name: 2.4.7 Disable Bluetooth Sharing
  tags: level_1
  osx_defaults:
    domain: com.apple.Bluetooth
    key: PrefKeyServicesEnabled
    type: int
    value: '0'
  become_user: target_user
  become: true

- name: "2.4.8 Disable File Sharing"
  tags: level_1
  command: launchctl unload -w /System/Library/LaunchDaemons/com.apple.smbd.plist

- name: "2.4.9 Disable Remote Management"
  tags: level_1
  command: /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -deactivate -stop 

- name: 2.4.10 Disable Content Caching 
  tags: level_2
  command: AssetCacheManagerUtil deactivate
  ignore_errors: yes

- name: 2.4.11 Disable Media Sharing
  tags: level_2 
  osx_defaults: 
    domain: com.apple.amp.mediasharingd
    key: home-sharing-enabled
    type: bool
    value: 'false'
  become_user: target_user
  become: true 

- name: "2.4.12 Ensure AirDrop is Disabled"
  tags: level_1
  osx_defaults:
    domain: com.apple.NetworkBrowser
    key: DisableAirDrop
    type: bool
    value: 'true' 
  become_user: target_user
  become: true

- name: "2.5.2.1 Enable Gatekeeper"
  tags: level_1
  command: spctl --master-enable

- name: "2.5.2.2 Enable Firewall"
  tags: level_1
  osx_defaults:
    domain: /Library/Preferences/com.apple.alf
    key: globalstate
    type: int
    value: '2' 

- name: "2.5.2.3 Enable Firewall Stealth Mode"
  tags: level_1
  command: /usr/libexec/ApplicationFirewall/socketfilterfw --setstealthmode on

- name: 2.5.3 Enable Location Services 
  tags: level_2
  command: launchctl load -w /System/Library/LaunchDaemons/com.apple.locationd.plist

- name: 2.5.5 Disable sending diagnostic and usage data to Apple
  tags: level_2
  shell: |
    defaults write /Library/Application\ Support/CrashReporter/DiagnosticMessagesHistory.plist AutoSubmit -bool false
    chmod 644 /Library/Application\ Support/CrashReporter/DiagnosticMessagesHistory.plist
    chgrp admin /Library/Application\ Support/CrashReporter/DiagnosticMessagesHistory.plist

- name: 2.5.6 Limit Ad tracking and personalized Ads
  tags: level_1
  osx_defaults:
    domain: com.apple.Adlib.plist
    key: allowApplePersonalizedAdvertising
    type: bool
    value: 'false'
  become_user: target_user
  become: true      

- name: "2.8 Disable Wake for network access"
  tags: level_1
  command: pmset -a womp 0

- name: "2.9 Disable Power Nap"
  tags: level_1
  command: pmset -a powernap 0 

- name: 2.10 Enable Secure Keyboard Entry in terminal.app
  tags: level_1
  osx_defaults: 
    domain: Terminal
    key: SecureKeyboardEntry
    type: bool
    value: true
  become_user: target_user
  become: true    

- name: 2.12 Automatic Actions for Optical Media 
  tags: level_1
  shell: |
    su "{{ target_user }}"
    defaults write /Users/$user/Library/Preferences/com.apple.digihub "{{ item.1 }}" -dict action 1
  with_nested:
    - ["com.apple.digihub.blank.cd.appeared", "com.apple.digihub.blank.dvd.appeared", "com.apple.digihub.cd.music.appeared", "com.apple.digihub.cd.picture.appeared", "com.apple.digihub.dvd.video.appeared"]

- name: 2.13 Review Siri Settings (1)
  tags: level_1
  osx_defaults:
    domain: com.apple.assistant.support.plist
    key: 'Assistant Enabled'
    type: bool
    value: 'false' 
  become_user: target_user
  become: true

- name: 2.13 Review Siri Settings (2) 
  tags: level_1
  osx_defaults:
    domain: com.apple.Siri.plist LockscreenEnabled
    key: LockscreenEnabled
    type: bool
    value: 'false' 
  become_user: target_user
  become: true

- name: 2.13 Review Siri Settings (3)
  tags: level_1
  osx_defaults:
    domain: com.apple.Siri.plist
    key: StatusMenuVisible
    type: bool
    value: 'false' 
  become_user: 'target_user'
  become: true

- name: 2.13 Review Siri Settings (4)
  tags: level_1
  osx_defaults:
    domain: com.apple.Siri.plist
    key: VoiceTriggerUserEnabled
    type: bool
    value: 'false'
  become_user: target_user
  become: true

- name: 2.13 Review Siri Settings (5)
  tags: level_1 
  command: |
    su "{{ target_user }}""
    killall -HUP cfprefsd
    killall SystemUIServer