- name: "2.2.1 Enable Set time and date automatically"
  command: "{{ item }}"
  with_items:
    - systemsetup -setnetworktimeserver time.apple.com
    - systemsetup -setusingnetworktime on

- name: "2.2.2 Ensure time set is within appropriate limits"
  command: systemsetup -getnetworktimeserver

- name: "2.3.1 Set an inactivity interval of 20 minutes or less for the screen saver"
  command: defaults -currentHost read com.apple.screensaver idleTime

- name: "2.4.1 Disable Removte Apple Events"
  command: systemsetup -setremoteappleevents off

- name: "2.4.2 Disable Internet Sharing"
  command: defaults write /Library/Preferences/SystemConfiguration/com.apple.nat NAT -dict Enabled -int 0

- name: "2.4.3 Disable Screen Sharing"
  command: launchctl disable system/com.apple.screensharing

- name: "2.4.4 Disable printer Sharing"
  command: cupsctl --no-share-printers

- name: "2.4.5 Disable Remote Login"
  command: yes | systemsetup -setremotelogin off

#note for 2.4.6 a reboot is required to have the service be unchecked. 
- name: "2.4.6 Disable DVD or CD Sharing"
  command: launcherctl disable system/com.apple.ODSAgent

#- name: "2.4.7 Disable Bluetooth Sharing"
 #command: "{{ item }}"
 # with_items: 
  #  - users=$(dscl . list /Users | grep -v '^_' | grep -v 'daemon' | grep -v 'nobody' | grep -v 'root')
  #  - for user in $users; do; su $user; defaults -currentHose write com.apple.Bluetooth PrefKeyServicesEnabled -bool false; done
# This is done in bash, this is another option that needs to be corrected

- name: "2.4.8 Disable File Sharing"
  command: launcherctl unload -w /System/Library/LaunchDaemons/com.apple.smbd.plist

- name: "2.4.9 Disable Remote Management"
  command: /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -deactive -stop 

#- name: "2.4.12 Ensure AirDrop is Disabled"
 # command: for user in $users; do; su $user; defaults write com.apple.NetworkBrowser DisableAirDrop -bool true; done
 # This is done in bash, this is another option that needs to be corrected

- name: "2.5.1.1 Enable FileVault"
  command: if fdesetup status == "FileVault is Off."; then; fdesetup enable; fi 

##- name: "2.5.1.2 Ensure all user storage APFS volumes are encrypted"
## 2.5.1.3 Ensure all user storage CoreStorage volumes are encrypted 

- name: "2.5.2.1 Enable Gatekeeper"
  command: spctl --master-enable

- name: "2.5.2.2 Enable Firewall"
  command: defaults write /Library/Preferences/com.apple.alf globalstate -int 2

- name: "2.5.2.3 Enable Firewall Stealth Mode"
  command: /usr/libexec/ApplicationFirewall/socketfilterfw --setstealthmode on

- name: "2.8 Disable Wake for network access"
  command: pmset -a womp 0

- name: "2.9 Disable Power Nap"
  command: pmset -a powernap 0 

