- name: Get Users
  shell: dscl . list /Users | grep -v '^_' | grep -v 'daemon' | grep -v 'nobody' | grep -v 'root'
  register: local_users

- name: Bluetooth Power state
  shell: defaults read /Library/Preferences/com.apple.Bluetooth ControllerPowerState
  register: bt_power

- name: Bluetooth Paired Devices
  shell: system_profiler SPBluetoothDataType | grep "Bluetooth:" -A 20 | grep Connectable
  register: bt_datatype

- name: Top Left Corner Value
  shell: defaults read com.apple.dock wvous-tl-corner
  register: cornerone 

- name: Bottom Left Corner Value
  shell: defaults read com.apple.dock wvous-bl-corner
  register: cornertwo

- name: Top Right Corner Value
  shell: defaults read com.apple.dock wvous-tr-corner
  register: cornerthree

- name: Bottom Right Corner Value
  shell: defaults read com.apple.dock wvous-br-corner
  register: cornerfour

- name: Fix Top Left Corner
  shell: defaults write com.apple.dock wvous-tl-corner -int 0
  register: corneronefix

- name: Fix Bottom Left Corner 
  shell: defaults write com.apple.dock wvous-bl-corner -int 0 
  register: cornertwofix 

- name: Fix Top Right Corner 
  shell: defaults write com.apple.dock wvous-tr-corner -int 0 
  register: cornerthreefix

- name: Fix Bottom Right Corner 
  shell: defaults write com.apple.dock wvous-br-corner -int 10
  register: cornerfourfix

- name: Check for FileVault Status
  command: fdesetup status 
  register: filevault_status

- name: 2.1.2 Show Bluetooth status in menu bar 
  tags: level_1
  shell: |
    su "{{ item }}"
    defaults -currentHost write com.apple.controlcenter.plist Bluetooth -int 18
  with_items: "{{ local_users.stdout_lines }}"

- name: "2.2.1 Enable Set time and date automatically"
  tags: level_1
  command: "{{ item }}"
  with_items:
    - systemsetup -setnetworktimeserver time.apple.com
    - systemsetup -setusingnetworktime on

- name: "2.2.2 Ensure time set is within appropriate limits"
  tags: level_1
  command: systemsetup -getnetworktimeserver

- name: "2.3.1 Set an inactivity interval of 20 minutes or less for the screen saver"
  tags: level_1
  shell: |
    su "{{ item }}"
    defaults -currentHost write com.apple.screensaver idleTime -int 1200
  with_items: "{{ local_users.stdout_lines}}"

- name: 2.3.2 Secure screen saver corners (Top Left) 
  tags: level_2
  shell: | 
    su "{{ item }}" 
    corneronefix
  with_items: "{{ local_users.stdout_lines}}"
  when: cornerone == 6

- name: 2.3.2 Secure screen saver corners (Bottom Left)
  tags: level_2
  shell: |
    su "{{ item }}"
    cornertwofix
  with_items: "{{ local_users.stdout_lines}}"
  when: cornertwo == 6

- name: 2.3.2 Secure screen saver corners (Top Right)
  tags: level_2
  shell: |
    su "{{ item }}"
    cornerthreefix
  with_items: "{{ local_users.stdout_lines}}"
  when: cornerthree == 6

- name: 2.3.2 Secure screen saver corners (Bottom Right)
  tags: level_2
  shell: |
    su "{{ item }}"
    cornerfourfix
  with_items: "{{ local_users.stdout_lines}}"
  when: cornerfour == 6

- name: "2.4.1 Disable Removte Apple Events"
  tags: level_1
  command: systemsetup -setremoteappleevents off

- name: "2.4.2 Disable Internet Sharing"
  tags: level_1
  command: defaults write /Library/Preferences/SystemConfiguration/com.apple.nat NAT -dict Enabled -int 0

- name: "2.4.3 Disable Screen Sharing"
  tags: level_1
  command: launchctl disable system/com.apple.screensharing

- name: "2.4.4 Disable printer Sharing"
  tags: level_1
  command: cupsctl --no-share-printers

- name: "2.4.5 Disable Remote Login"
  tags: level_1
  command: yes | systemsetup -setremotelogin off

- name: "2.4.6 Disable DVD or CD Sharing"
  tags: level_1
  command: launcherctl disable system/com.apple.ODSAgent

- name: 2.4.7 Disable Bluetooth Sharing
  tags: level_1
  shell: |
    su "{{ item }}"
    defaults -currentHost write com.apple.Bluetooth PrefKeyServicesEnabled -bool false
  with_items: "{{ local_users.stdout_lines}}"

- name: "2.4.8 Disable File Sharing"
  tags: level_1
  command: launcherctl unload -w /System/Library/LaunchDaemons/com.apple.smbd.plist

- name: "2.4.9 Disable Remote Management"
  tags: level_1
  command: /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -deactivate -stop 

- name: "2.4.12 Ensure AirDrop is Disabled"
  tags: level_1
  shell: |
    su "{{ item }}"
    defaults write com.apple.NetworkBrowser DisableAirDrop -bool true
  with_items: "{{ local_users.stdout_lines }}"

- name: "2.5.1.1 Enable FileVault"
  tags: level_1
  command: fdsetup enable
  when: filevault_status.stdout == "FileVault is Off." 

- name: "2.5.2.1 Enable Gatekeeper"
  tags: level_1
  command: spctl --master-enable

- name: "2.5.2.2 Enable Firewall"
  tags: level_1
  command: defaults write /Library/Preferences/com.apple.alf globalstate -int 2

- name: "2.5.2.3 Enable Firewall Stealth Mode"
  tags: level_1
  command: /usr/libexec/ApplicationFirewall/socketfilterfw --setstealthmode on

- name: 2.5.6 Limit Ad tracking and personalized Ads
  tags: level_1
  shell: |
    su "{{ item }}"
    defaults -currentHost write /Users/$user/Library/Preferences/com.apple.Adlib.plist allowApplePersonalizedAdvertising -bool false
  with_items: "{{ local_users.stdout_lines }}"


- name: "2.8 Disable Wake for network access"
  tags: level_1
  command: pmset -a womp 0

- name: "2.9 Disable Power Nap"
  tags: level_1
  command: pmset -a powernap 0 

- name: 2.10 Enable Secure Keyboard Entry in terminal.app
  tags: level_1
  shell: |
    su "{{ item }}"
    defaults write -app Terminal SecureKeyboardEntry -bool true
  with_items: "{{ local_users.stdout_lines }}"

- name: 2.12 Automatic Actions for Optical Media 
  tags: level_1
  shell: |
    su "{{ item.0 }}"
    defaults write /Users/$user/Library/Preferences/com.apple.digihub "{{ item.1 }}" -dict action 1
  with_nested:
    - "{{ local_users.stdout_lines }}"
    - ["com.apple.digihub.blank.cd.appeared", "com.apple.digihub.blank.dvd.appeared", "com.apple.digihub.cd.music.appeared", "com.apple.digihub.cd.picture.appeared", "com.apple.digihub.dvd.video.appeared"]


- name: 2.13 Review Siri Settings
  tags: level_1
  shell: |
    su "{{ item }}"
    defaults write com.apple.assistant.support.plist 'Assistant Enabled' -bool false
    defaults write com.apple.Siri.plist LockscreenEnabled -bool false
    defaults write com.apple.Siri.plist StatusMenuVisible -bool false
    defaults write com.apple.Siri.plist VoiceTriggerUserEnabled -bool false
    killall -HUP cfprefsd
    killall SystemUIServer
  with_items: "{{ local_users.stdout_lines }}"