- name: "2.2.1 Enable Set time and date automatically"
  command: 
  - systemsetup -setnetworktimeserver time.apple.com
  - systemsetup -setusingnetworktime on

- name: "2.2.2 Ensure time set is within appropriate limits"
  command: systemsetup -getnetworktimeserver

- name: "2.3.1 Set an inactivity interval of 20 minutes or less for the screen saver"
  command: defaults -currentHost read com.apple.screensaver idleTime