- name: 1.1 Verify all Apple-provided software is current
  command: softwareupdate -i -a

- name: 1.2 Enable Auto Update
  command: defaults write /Library/Preferences/com.apple.SoftwareUpdate AutomaticCheckEnabled -bool true

- name: 1.3