- hosts: localhost
  connection: local
  tasks:
    - debug:
        msg: Check we are running in the directory of the script
      failed_when: not ansible_env.PWD.endswith('/ansible')
      tags:
        - level_1
        - level_2
    - name: Set BASH as the default shell
      shell: chsh -s $(which bash) {{ lookup('env', 'USER') }}
      become: true
      tags:
        - level_1
        - level_2
    - name: Get Users
      shell: dscl . list /Users | grep -v '^_' | grep -v 'daemon' | grep -v 'nobody' | grep -v 'root'
      register: local_users
      tags:
        - level_1
        - level_2
    - name: Users
      set_fact: users="{{ local_users.stdout_lines }}"
      tags:
        - level_1
        - level_2


- hosts: localhost
  connection: local
  vars_files:
    - vars/org.yml
    - vars/defaults.yml
  roles:
    - 1.X
    - 2.X
    - 3.X
    - 4.X
    - 5.X
    - 6.X
